/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DisenioRouteImport } from './routes/disenio'
import { Route as IndexRouteImport } from './routes/index'

const DisenioRoute = DisenioRouteImport.update({
  id: '/disenio',
  path: '/disenio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disenio': typeof DisenioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disenio': typeof DisenioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disenio': typeof DisenioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disenio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disenio'
  id: '__root__' | '/' | '/disenio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisenioRoute: typeof DisenioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/disenio': {
      id: '/disenio'
      path: '/disenio'
      fullPath: '/disenio'
      preLoaderRoute: typeof DisenioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisenioRoute: DisenioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
